name: C/C++ CI for Lotus Compiler

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake and Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Generate build system
        run: cmake -G "Ninja" -S . -B build

      - name: Build project
        run: cmake --build build --config Release

      - name: Verify executable
        run: |
          if [ -f "./bin/lotus" ]; then
            echo "Executable found."
          else
            echo "Executable not found."
            exit 1
          fi
